apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: tomcat
  name: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      run: tomcat
  template:
    metadata:
      labels:
        run: tomcat
    spec:
      containers:
      - image: tomcat:test
        imagePullPolicy: IfNotPresent
        name: tomcat
        command:
        - /usr/local/tomcat/bin/catalina.sh
        - run
        ports:
          - containerPort: 8080
            name: "htps"
        volumeMounts:
        - name: logvol
          mountPath: /usr/local/tomcat/logs
        - name: stormount
          mountPath: /mnt
      - name: logcollector
        image: jasko/log-collect:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LOCATION
          value: /opt/logs
        - name: INTERVAL
          value: "5"
	- name: LOGOPT
          value: "-a"
        volumeMounts:
        - name: logvol
          mountPath: /opt/logs
        - name: stormount
          mountPath: /mnt
      volumes:
      - name: logvol
        emptyDir: {}
      - name: stormount
        hostPath:
          path: /opt/cephfs/projA
